CREATE TABLE slots (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_date DATE          NOT NULL,
    service_time VARCHAR2(5)   NOT NULL,
    capacity     NUMBER(5)     NOT NULL,
    seats_taken  NUMBER(5)     DEFAULT 0 NOT NULL,
    version      NUMBER(10)    DEFAULT 0 NOT NULL,
    CONSTRAINT uq_slots_datetime UNIQUE (service_date, service_time),
    CONSTRAINT ck_slots_seats CHECK (seats_taken >= 0 AND seats_taken <= capacity)
);

CREATE TABLE bookings (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_id         NUMBER        NOT NULL,
    phone           VARCHAR2(20)  NOT NULL,
    party_size      NUMBER(3)     NOT NULL,
    status          VARCHAR2(20)  NOT NULL,
    deposit_cents   NUMBER(10)    NOT NULL,
    idempotency_key VARCHAR2(64)  NOT NULL,
    created_at      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    expires_at      TIMESTAMP     NOT NULL,
    CONSTRAINT fk_bookings_slot FOREIGN KEY (slot_id) REFERENCES slots(id),
    CONSTRAINT uq_bookings_idempotency UNIQUE (idempotency_key),
    CONSTRAINT ck_bookings_party CHECK (party_size > 0),
    CONSTRAINT ck_bookings_status CHECK (status IN
        ('PENDING_DEPOSIT','CONFIRMED','EXPIRED','CANCELLED'))
);

CREATE INDEX ix_bookings_sweep ON bookings (status, expires_at);
