apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-from-gate-only
spec:
  podSelector:
    matchLabels: { app: redis }
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector:
            matchLabels: { app: queue-gate }
      ports:
        - protocol: TCP
          port: 6379
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: booking-service-from-gate-only
spec:
  podSelector:
    matchLabels: { app: booking-service }
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector:
            matchLabels: { app: queue-gate }
      ports:
        - protocol: TCP
          port: 8081
