package dev.marwan.console.ops;

import dev.marwan.console.ConsoleProperties;
import dev.marwan.console.cluster.KubernetesAccess;
import org.junit.jupiter.api.Test;
import org.springframework.web.client.RestClient;

import java.time.Clock;
import java.time.Duration;
import java.time.Instant;
import java.time.ZoneOffset;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.BDDMockito.given;
import static org.mockito.Mockito.mock;

class LoadOpsTest {

    private final KubernetesAccess kubernetes = mock(KubernetesAccess.class);

    private final LoadOps ops = new LoadOps(
            properties(),
            kubernetes,
            RestClient.builder().baseUrl("http://queue-gate:8080").build(),
            Clock.fixed(Instant.parse("2026-09-05T12:00:00Z"), ZoneOffset.UTC));

    /**
     * One run per drop, enforced by the name rather than by a counter.
     *
     * This is the whole concurrency control: a second create of the same name
     * is refused by the API server, which cannot get out of step with reality
     * the way a number this console kept would.
     */
    @Test
    void theJobIsNamedAfterTheDrop() {
        assertThat(LoadOps.jobName("d-abc12345")).isEqualTo("load-d-abc12345");
        assertThat(LoadOps.jobName("default")).isEqualTo("load-default");
    }

    /**
     * Drop ids are generated by the gate, but the name has to be a legal
     * Kubernetes object name whatever arrives: lowercase, no leading or
     * trailing dash, and short enough to leave room for the pod's own suffixes.
     */
    @Test
    void theJobNameIsALegalKubernetesName() {
        String name = LoadOps.jobName("D-ABC_123!!");

        assertThat(name).isEqualTo("load-d-abc-123");
        assertThat(name).matches("[a-z0-9]([-a-z0-9]*[a-z0-9])?");
        assertThat(LoadOps.jobName("!!!")).isEqualTo("load-unnamed");
        assertThat(LoadOps.jobName("x".repeat(200))).hasSizeLessThanOrEqualTo(53);
    }

    /**
     * A bigger run must cost more CPU, or the largest offer could never be the
     * one the quota refuses — and the constraints panel would have nothing to
     * explain, which is the point of offering it.
     */
    @Test
    void aBiggerRunAsksTheSchedulerForMore() {
        assertThat(LoadOps.cpuMillis(200)).isEqualTo(200);
        assertThat(LoadOps.cpuMillis(1000)).isEqualTo(400);
        assertThat(LoadOps.cpuMillis(3000)).isEqualTo(800);
        assertThat(LoadOps.memoryMebibytes(200)).isLessThan(LoadOps.memoryMebibytes(3000));
    }

    /**
     * Reading a run's state must never fail the request. The page polls this
     * beside the queue numbers, and those come from services that have nothing
     * to do with the Kubernetes API.
     */
    @Test
    void anUnreadableClusterIsReportedRatherThanThrown() {
        given(kubernetes.client()).willThrow(new IllegalStateException("no such host: kubernetes"));

        LoadRun run = ops.status("d-abc12345");

        assertThat(run.available()).isFalse();
        assertThat(run.detail()).contains("no such host");
        assertThat(run.phase()).isEqualTo(LoadRun.Phase.NONE);
    }

    /** 200 is the measured ceiling of usefulness, so it is what an empty body means. */
    @Test
    void theDefaultIsTheMeasuredCeiling() {
        assertThat(LoadOps.DEFAULT_VUS).isEqualTo(200);
    }

    private static ConsoleProperties properties() {
        return new ConsoleProperties("http://booking-service:8081", "http://queue-gate:8080",
                "default", 1, Duration.ofSeconds(2), Duration.ofSeconds(1), "marwanbukhori-dev",
                "s3cret-demo-key", "compute-deploy", "grafana/k6:0.53.0",
                new ConsoleProperties.Pool("booking-service", 5, 20));
    }
}
