// Generated by deploy/scripts/capture-cicd-runs.py from real runs. Do not edit by hand;
// re-run the script to refresh the example.

export interface CapturedStep {
  name: string;
  result: string;
  seconds: number;
  /** [GitHub's line number, or null for an elision marker; the line] */
  log: [number | null, string][];
  explain: string;
}

export interface CapturedRun {
  kind: 'ci' | 'cd' | 'rollback';
  /** Shown above the steps; empty for the normal runs. */
  note: string;
  workflow: string;
  job: string;
  runId: number;
  attempt: number;
  url: string;
  commit: string;
  startedAt: string;
  result: string;
  seconds: number;
  steps: CapturedStep[];
}

export const CAPTURED_RUNS: CapturedRun[] = [
 {
  "kind": "ci",
  "note": "",
  "workflow": "ci",
  "job": "build",
  "runId": 36157265585,
  "attempt": 1,
  "url": "https://github.com/marwanbukhori/rembayung-queue/actions/runs/36157265585",
  "commit": "7983f03",
  "startedAt": "2026-09-25T15:54:07Z",
  "result": "success",
  "seconds": 221,
  "steps": [
   {
    "name": "Set up job",
    "result": "success",
    "seconds": 4,
    "log": [
     [
      1,
      "Current runner version: '2.337.0'"
     ],
     [
      2,
      "Runner Image Provisioner"
     ],
     [
      3,
      "Hosted Compute Agent"
     ],
     [
      4,
      "Version: 20260828.587"
     ],
     [
      5,
      "Commit: abac92662cab4cc7352de4f9f9d2e2419aad9c29"
     ],
     [
      6,
      "Build Date: 2026-08-28T16:44:25Z"
     ],
     [
      7,
      "Worker ID: {703e5543-44c6-4466-aa7e-abbef42b3c77}"
     ],
     [
      8,
      "Azure Region: centralus"
     ],
     [
      9,
      "Operating System"
     ],
     [
      10,
      "Ubuntu"
     ],
     [
      11,
      "24.04.5"
     ],
     [
      12,
      "LTS"
     ],
     [
      13,
      "Runner Image"
     ],
     [
      14,
      "Image: ubuntu-24.04"
     ],
     [
      null,
      "… 10 lines …"
     ],
     [
      25,
      "Prepare all required actions"
     ],
     [
      26,
      "Getting action download info"
     ],
     [
      27,
      "Download action repository 'actions/checkout@v4' (SHA:11d5960a326750d5838078e36cf38b85af677262)"
     ],
     [
      28,
      "Download action repository 'actions/setup-java@v4' (SHA:cf277c60eb25467037889841efdb72551f06f6c3)"
     ],
     [
      29,
      "Download action repository 'docker/login-action@v3' (SHA:c94ce9fb468520275223c153574b00df6fe4bcc9)"
     ],
     [
      30,
      "Download action repository 'docker/setup-buildx-action@v3' (SHA:8d2750c68a42422c14e847fe6c8ac0403b4cbd6f)"
     ],
     [
      31,
      "Download action repository 'docker/build-push-action@v6' (SHA:10e90e3645eae34f1e60eeb005ba3a3d33f178e8)"
     ],
     [
      32,
      "Complete job name: build"
     ]
    ],
    "explain": "GitHub provisions a fresh ubuntu-latest runner for this one job. Nothing carries over from the previous run, so every build starts from a clean machine."
   },
   {
    "name": "Run actions/checkout@v4",
    "result": "success",
    "seconds": 1,
    "log": [
     [
      1,
      "Run actions/checkout@v4"
     ],
     [
      2,
      "with:"
     ],
     [
      3,
      "  repository: marwanbukhori/rembayung-queue"
     ],
     [
      4,
      "  token: ***"
     ],
     [
      5,
      "  ssh-strict: true"
     ],
     [
      6,
      "  ssh-user: git"
     ],
     [
      7,
      "  persist-credentials: true"
     ],
     [
      8,
      "  clean: true"
     ],
     [
      9,
      "  sparse-checkout-cone-mode: true"
     ],
     [
      10,
      "  fetch-depth: 1"
     ],
     [
      11,
      "  fetch-tags: false"
     ],
     [
      12,
      "  show-progress: true"
     ],
     [
      13,
      "  lfs: false"
     ],
     [
      14,
      "  submodules: false"
     ],
     [
      null,
      "… 43 lines …"
     ],
     [
      58,
      "[command]/usr/bin/git sparse-checkout disable"
     ],
     [
      59,
      "[command]/usr/bin/git config --local --unset-all extensions.worktreeConfig"
     ],
     [
      60,
      "Checking out the ref"
     ],
     [
      61,
      "[command]/usr/bin/git checkout --progress --force -B main refs/remotes/origin/main"
     ],
     [
      62,
      "Switched to a new branch 'main'"
     ],
     [
      63,
      "branch 'main' set up to track 'origin/main'."
     ],
     [
      64,
      "[command]/usr/bin/git log -1 --format=%H"
     ],
     [
      65,
      "7983f0346f1715a0b44d25361ea1a5e0a74e36af"
     ]
    ],
    "explain": "Checks out the exact commit that was pushed. Every image tag later in the pipeline is this commit's SHA."
   },
   {
    "name": "Set up JDK 25",
    "result": "success",
    "seconds": 2,
    "log": [
     [
      1,
      "Run actions/setup-java@v4"
     ],
     [
      2,
      "with:"
     ],
     [
      3,
      "  distribution: temurin"
     ],
     [
      4,
      "  java-version: 25"
     ],
     [
      5,
      "  cache: maven"
     ],
     [
      6,
      "  java-package: jdk"
     ],
     [
      7,
      "  check-latest: false"
     ],
     [
      8,
      "  server-id: github"
     ],
     [
      9,
      "  server-username: GITHUB_ACTOR"
     ],
     [
      10,
      "  server-password: GITHUB_TOKEN"
     ],
     [
      11,
      "  overwrite-settings: true"
     ],
     [
      12,
      "  job-status: success"
     ],
     [
      13,
      "  token: ***"
     ],
     [
      14,
      "##[warning]setup-java v4 is deprecated and will no longer receive updates. Please migrate to actions/setup-java@v5."
     ],
     [
      null,
      "… 15 lines …"
     ],
     [
      30,
      "Cache hit for: setup-java-Linux-x64-maven-17a2d01f1d1b96de0964dcb589cebb862608b776154b498a0e403eafe81ce357"
     ],
     [
      31,
      "(node:2042) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API…"
     ],
     [
      32,
      "Received 83886080 of 152208057 (55.1%), 80.0 MBs/sec"
     ],
     [
      33,
      "Received 152208057 of 152208057 (100.0%), 101.9 MBs/sec"
     ],
     [
      34,
      "Cache Size: ~145 MB (152208057 B)"
     ],
     [
      35,
      "[command]/usr/bin/tar -xf /home/runner/work/_temp/d5c9bd7f-f906-4f12-818e-888e9342244b/cache.tzst -P -C /home/runner/work/rembayung-queue/rembayung-queue --use-…"
     ],
     [
      36,
      "Cache restored successfully"
     ],
     [
      37,
      "Cache restored from key: setup-java-Linux-x64-maven-17a2d01f1d1b96de0964dcb589cebb862608b776154b498a0e403eafe81ce357"
     ]
    ],
    "explain": "Installs Temurin 25 and restores the Maven cache keyed on the pom files, so dependencies download once rather than on every run."
   },
   {
    "name": "Test booking-service",
    "result": "success",
    "seconds": 118,
    "log": [
     [
      1,
      "Run ./mvnw --batch-mode verify"
     ],
     [
      2,
      "./mvnw --batch-mode verify"
     ],
     [
      3,
      "shell: /usr/bin/bash -e {0}"
     ],
     [
      4,
      "env:"
     ],
     [
      63,
      "15:54:32.362 [main] INFO tc.testcontainers/ryuk:0.14.0 -- Container testcontainers/ryuk:0.14.0 started in PT0.406654586S"
     ],
     [
      94,
      "15:55:54.594 [main] INFO tc.gvenzl/oracle-free:23-slim-faststart -- Container gvenzl/oracle-free:23-slim-faststart started in PT28.173679214S"
     ],
     [
      303,
      "[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 100.2 s -- in dev.marwan.booking.IdempotencyTest"
     ],
     [
      910,
      "[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.295 s -- in dev.marwan.booking.ConcurrencyInvariantTest"
     ],
     [
      959,
      "[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.279 s -- in dev.marwan.booking.ConfirmExpireRaceTest"
     ],
     [
      998,
      "[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.234 s -- in dev.marwan.booking.HealthProbeTest"
     ],
     [
      1159,
      "[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.878 s -- in dev.marwan.booking.ExpirySweeperTest"
     ],
     [
      1166,
      "[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.077 s -- in dev.marwan.booking.SchemaMigrationTest"
     ],
     [
      1173,
      "[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.114 s -- in dev.marwan.booking.InternalControllerTest"
     ],
     [
      1176,
      "[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.199 s -- in dev.marwan.booking.config.BookingMetricsTest"
     ],
     [
      1178,
      "[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 s -- in dev.marwan.booking.PoolExhaustionTest"
     ],
     [
      1185,
      "[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.074 s -- in dev.marwan.booking.service.SlotStatesQueryTest"
     ],
     [
      1187,
      "[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.152 s -- in dev.marwan.booking.service.SlotStateProviderTest"
     ],
     [
      1194,
      "[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.056 s -- in dev.marwan.booking.SlotRepositoryTest"
     ],
     [
      1205,
      "[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.260 s -- in dev.marwan.booking.BookingControllerTest"
     ],
     [
      1217,
      "[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.100 s -- in dev.marwan.booking.BookingServiceTest"
     ],
     [
      1257,
      "[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.683 s -- in dev.marwan.booking.ReadinessUnderLoadTest"
     ],
     [
      1259,
      "[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.009 s -- in dev.marwan.booking.OverloadResponseTest"
     ],
     [
      1263,
      "[INFO] Tests run: 73, Failures: 0, Errors: 0, Skipped: 0"
     ],
     [
      1273,
      "[INFO] BUILD SUCCESS"
     ],
     [
      1275,
      "[INFO] Total time:  01:54 min"
     ]
    ],
    "explain": "The slowest step, on purpose: Testcontainers starts a real Oracle Free and the tests run against it. A mock would accept SQL that Oracle rejects, and the seat-claiming query is exactly the SQL that matters."
   },
   {
    "name": "Test queue-gate",
    "result": "success",
    "seconds": 17,
    "log": [
     [
      1,
      "Run ./mvnw --batch-mode verify"
     ],
     [
      2,
      "./mvnw --batch-mode verify"
     ],
     [
      3,
      "shell: /usr/bin/bash -e {0}"
     ],
     [
      4,
      "env:"
     ],
     [
      54,
      "15:56:18.194 [main] INFO tc.testcontainers/ryuk:0.14.0 -- Container testcontainers/ryuk:0.14.0 started in PT0.717294796S"
     ],
     [
      81,
      "15:56:20.125 [main] INFO tc.redis:7-alpine -- Container redis:7-alpine started in PT0.151597185S"
     ],
     [
      510,
      "[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.770 s -- in dev.marwan.gate.QueueServiceTest"
     ],
     [
      517,
      "[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.035 s -- in dev.marwan.gate.RedisReachableTest"
     ],
     [
      544,
      "[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.647 s -- in dev.marwan.gate.HealthProbeTest"
     ],
     [
      573,
      "[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.356 s -- in dev.marwan.gate.BookingProxyDownstreamUnavailableTest"
     ],
     [
      586,
      "[INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.216 s -- in dev.marwan.gate.web.InternalControllerTest"
     ],
     [
      597,
      "[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.150 s -- in dev.marwan.gate.web.InternalGuardTest"
     ],
     [
      599,
      "[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 s -- in dev.marwan.gate.AdmissionTest"
     ],
     [
      614,
      "[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.130 s -- in dev.marwan.gate.queue.MultiDropTest"
     ],
     [
      1021,
      "[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.697 s -- in dev.marwan.gate.queue.RushFormsAQueueTest"
     ],
     [
      1028,
      "[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.079 s -- in dev.marwan.gate.queue.DropRegistryTest"
     ],
     [
      1030,
      "[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.403 s -- in dev.marwan.gate.queue.QueueStateProviderTest"
     ],
     [
      1032,
      "[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.011 s -- in dev.marwan.gate.queue.QueueStateTest"
     ],
     [
      1292,
      "[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.344 s -- in dev.marwan.gate.QueueControllerTest"
     ],
     [
      1607,
      "[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.284 s -- in dev.marwan.gate.AdmissionServiceTest"
     ],
     [
      1644,
      "[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.330 s -- in dev.marwan.gate.BookingProxyControllerTest"
     ],
     [
      1648,
      "[INFO] Tests run: 84, Failures: 0, Errors: 0, Skipped: 0"
     ],
     [
      1658,
      "[INFO] BUILD SUCCESS"
     ],
     [
      1660,
      "[INFO] Total time:  16.628 s"
     ]
    ],
    "explain": "queue-gate's tests, against a real Redis started by Testcontainers. The queue lives in Redis, so that is where it is tested."
   },
   {
    "name": "Test console",
    "result": "success",
    "seconds": 12,
    "log": [
     [
      1,
      "Run ./mvnw --batch-mode verify"
     ],
     [
      2,
      "./mvnw --batch-mode verify"
     ],
     [
      3,
      "shell: /usr/bin/bash -e {0}"
     ],
     [
      4,
      "env:"
     ],
     [
      36,
      "[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.227 s -- in dev.marwan.console.objects.NetworkDescriberTest"
     ],
     [
      38,
      "[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.081 s -- in dev.marwan.console.objects.WorkloadDescriberTest"
     ],
     [
      40,
      "[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 s -- in dev.marwan.console.objects.ScopeTest"
     ],
     [
      42,
      "[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s -- in dev.marwan.console.objects.ObjectKindTest"
     ],
     [
      44,
      "[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.163 s -- in dev.marwan.console.objects.PodLogsTest"
     ],
     [
      46,
      "[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.086 s -- in dev.marwan.console.objects.ObjectsProviderTest"
     ],
     [
      48,
      "[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.031 s -- in dev.marwan.console.objects.LogLinesTest"
     ],
     [
      77,
      "[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.076 s -- in dev.marwan.console.objects.ObjectsControllerTest"
     ],
     [
      79,
      "[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.014 s -- in dev.marwan.console.objects.EventLinesTest"
     ],
     [
      81,
      "[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.021 s -- in dev.marwan.console.observability.ObservabilityProbeTest"
     ],
     [
      104,
      "[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.263 s -- in dev.marwan.console.web.DemoKeyControllerOffTest"
     ],
     [
      127,
      "[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.260 s -- in dev.marwan.console.web.StateControllerTest"
     ],
     [
      150,
      "[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.152 s -- in dev.marwan.console.web.DemoKeyControllerTest"
     ],
     [
      173,
      "[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.030 s -- in dev.marwan.console.web.DocsControllerTest"
     ],
     [
      196,
      "[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.338 s -- in dev.marwan.console.auth.KeyFilterTest"
     ],
     [
      198,
      "[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s -- in dev.marwan.console.auth.AccessKeyTest"
     ],
     [
      200,
      "[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.050 s -- in dev.marwan.console.ops.LoadOpsTest"
     ],
     [
      206,
      "[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.056 s -- in dev.marwan.console.ops.DropOpsTest"
     ],
     [
      208,
      "[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.010 s -- in dev.marwan.console.state.ClusterStateTest"
     ],
     [
      213,
      "[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 s -- in dev.marwan.console.state.ClusterStateProviderTest"
     ],
     [
      218,
      "[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.039 s -- in dev.marwan.console.state.DemoStateProviderTest"
     ],
     [
      220,
      "[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s -- in dev.marwan.console.state.DemoStateTest"
     ],
     [
      243,
      "[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.224 s -- in dev.marwan.console.metrics.MetricsControllerTest"
     ],
     [
      245,
      "[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 s -- in dev.marwan.console.metrics.PromTextTest"
     ],
     [
      247,
      "[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.103 s -- in dev.marwan.console.metrics.PodReadingsTest"
     ],
     [
      249,
      "[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.050 s -- in dev.marwan.console.metrics.MetricsServiceTest"
     ],
     [
      251,
      "[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 s -- in dev.marwan.console.metrics.PromJsonTest"
     ],
     [
      255,
      "[INFO] Tests run: 149, Failures: 0, Errors: 0, Skipped: 0"
     ],
     [
      265,
      "[INFO] BUILD SUCCESS"
     ],
     [
      267,
      "[INFO] Total time:  10.652 s"
     ]
    ],
    "explain": "The console's tests: the key filter, the demo-key endpoint, the Prometheus and pod readers."
   },
   {
    "name": "Package jars",
    "result": "success",
    "seconds": 7,
    "log": [
     [
      1,
      "Run booking-service/mvnw --batch-mode -f booking-service -DskipTests package"
     ],
     [
      2,
      "booking-service/mvnw --batch-mode -f booking-service -DskipTests package"
     ],
     [
      3,
      "queue-gate/mvnw     --batch-mode -f queue-gate     -DskipTests package"
     ],
     [
      4,
      "console/mvnw        --batch-mode -f console        -DskipTests package"
     ],
     [
      5,
      "shell: /usr/bin/bash -e {0}"
     ],
     [
      6,
      "env:"
     ],
     [
      7,
      "  JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/25.0.4-1/x64"
     ],
     [
      8,
      "  JAVA_HOME_25_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/25.0.4-1/x64"
     ],
     [
      9,
      "[INFO] Scanning for projects..."
     ],
     [
      10,
      "[INFO] "
     ],
     [
      11,
      "[INFO] ---------------------< dev.marwan:booking-service >---------------------"
     ],
     [
      12,
      "[INFO] Building booking-service 0.1.0-SNAPSHOT"
     ],
     [
      13,
      "[INFO]   from pom.xml"
     ],
     [
      14,
      "[INFO] --------------------------------[ jar ]---------------------------------"
     ],
     [
      null,
      "… 88 lines …"
     ],
     [
      103,
      "[INFO] Replacing main artifact /home/runner/work/rembayung-queue/rembayung-queue/console/target/console-0.1.0-SNAPSHOT.jar with repackaged archive, adding neste…"
     ],
     [
      104,
      "[INFO] The original artifact has been renamed to /home/runner/work/rembayung-queue/rembayung-queue/console/target/console-0.1.0-SNAPSHOT.jar.original"
     ],
     [
      105,
      "[INFO] ------------------------------------------------------------------------"
     ],
     [
      106,
      "[INFO] BUILD SUCCESS"
     ],
     [
      107,
      "[INFO] ------------------------------------------------------------------------"
     ],
     [
      108,
      "[INFO] Total time:  1.289 s"
     ],
     [
      109,
      "[INFO] Finished at: 2026-09-25T15:56:48Z"
     ],
     [
      110,
      "[INFO] ------------------------------------------------------------------------"
     ]
    ],
    "explain": "Builds the three Spring Boot jars. From here on the steps run only on main or a manual dispatch; a branch push stops after the tests and never touches the registry."
   },
   {
    "name": "Log in to ghcr.io",
    "result": "success",
    "seconds": 1,
    "log": [
     [
      1,
      "Run docker/login-action@v3"
     ],
     [
      2,
      "with:"
     ],
     [
      3,
      "  registry: ghcr.io"
     ],
     [
      4,
      "  username: marwanbukhori"
     ],
     [
      5,
      "  password: ***"
     ],
     [
      6,
      "  logout: true"
     ],
     [
      7,
      "env:"
     ],
     [
      8,
      "  JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/25.0.4-1/x64"
     ],
     [
      9,
      "  JAVA_HOME_25_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/25.0.4-1/x64"
     ],
     [
      10,
      "Logging into ghcr.io..."
     ],
     [
      11,
      "(node:4721) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead."
     ],
     [
      12,
      "(Use `node --trace-deprecation ...` to show where the warning was created)"
     ],
     [
      13,
      "Login Succeeded!"
     ]
    ],
    "explain": "Logs in to GitHub's container registry with the job's own short-lived GITHUB_TOKEN. There is no stored registry password to leak or rotate."
   },
   {
    "name": "Set up Buildx",
    "result": "success",
    "seconds": 7,
    "log": [
     [
      1,
      "Run docker/setup-buildx-action@v3"
     ],
     [
      2,
      "with:"
     ],
     [
      3,
      "  driver: docker-container"
     ],
     [
      4,
      "  use: true"
     ],
     [
      5,
      "  keep-state: false"
     ],
     [
      6,
      "  cache-binary: true"
     ],
     [
      7,
      "  cleanup: true"
     ],
     [
      8,
      "  install: false"
     ],
     [
      9,
      "env:"
     ],
     [
      10,
      "  JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/25.0.4-1/x64"
     ],
     [
      11,
      "  JAVA_HOME_25_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/25.0.4-1/x64"
     ],
     [
      12,
      "(node:4741) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead."
     ],
     [
      13,
      "(Use `node --trace-deprecation ...` to show where the warning was created)"
     ],
     [
      14,
      "Docker info"
     ],
     [
      null,
      "… 216 lines …"
     ],
     [
      231,
      "    }"
     ],
     [
      232,
      "  ],"
     ],
     [
      233,
      "  \"name\": \"builder-ec3ced38-5b27-4394-8b8a-f4ac53c3f892\","
     ],
     [
      234,
      "  \"driver\": \"docker-container\","
     ],
     [
      235,
      "  \"lastActivity\": \"2026-09-25T15:56:51.000Z\""
     ],
     [
      236,
      "}"
     ],
     [
      237,
      "BuildKit version"
     ],
     [
      238,
      "builder-ec3ced38-5b27-4394-8b8a-f4ac53c3f8920: v0.32.2"
     ]
    ],
    "explain": "Prepares Docker's Buildx builder. Each build step below asks it for linux/amd64, the architecture the OpenShift nodes run."
   },
   {
    "name": "Build and push booking-service",
    "result": "success",
    "seconds": 12,
    "log": [
     [
      1,
      "Run docker/build-push-action@v6"
     ],
     [
      2,
      "with:"
     ],
     [
      3,
      "  context: ./booking-service"
     ],
     [
      4,
      "  platforms: linux/amd64"
     ],
     [
      5,
      "  push: true"
     ],
     [
      6,
      "  tags: ghcr.io/marwanbukhori/booking-service:7983f0346f1715a0b44d25361ea1a5e0a74e36af"
     ],
     [
      7,
      "  load: false"
     ],
     [
      8,
      "  no-cache: false"
     ],
     [
      9,
      "  pull: false"
     ],
     [
      10,
      "  github-token: ***"
     ],
     [
      11,
      "env:"
     ],
     [
      12,
      "  JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/25.0.4-1/x64"
     ],
     [
      13,
      "  JAVA_HOME_25_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/25.0.4-1/x64"
     ],
     [
      14,
      "(node:5215) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead."
     ],
     [
      null,
      "… 693 lines …"
     ],
     [
      708,
      "  },"
     ],
     [
      709,
      "  \"containerimage.digest\": \"sha256:0c46206550edc9d919bbaa600e2c11afdbb1c980a3a4726cbc4be184e433c05f\","
     ],
     [
      710,
      "  \"image.name\": \"ghcr.io/marwanbukhori/booking-service:7983f0346f1715a0b44d25361ea1a5e0a74e36af\""
     ],
     [
      711,
      "}"
     ],
     [
      712,
      "Reference"
     ],
     [
      713,
      "builder-ec3ced38-5b27-4394-8b8a-f4ac53c3f892/builder-ec3ced38-5b27-4394-8b8a-f4ac53c3f8920/y1zpcpwpn12bnjmqgzzqbasb7"
     ],
     [
      714,
      "Check build summary support"
     ],
     [
      715,
      "Build summary supported!"
     ]
    ],
    "explain": "Builds booking-service's image and pushes it tagged with the full commit SHA, never latest. An immutable tag is what lets CD say exactly what is running, and roll back to it."
   },
   {
    "name": "Build and push queue-gate",
    "result": "success",
    "seconds": 6,
    "log": [
     [
      1,
      "Run docker/build-push-action@v6"
     ],
     [
      2,
      "with:"
     ],
     [
      3,
      "  context: ./queue-gate"
     ],
     [
      4,
      "  platforms: linux/amd64"
     ],
     [
      5,
      "  push: true"
     ],
     [
      6,
      "  tags: ghcr.io/marwanbukhori/queue-gate:7983f0346f1715a0b44d25361ea1a5e0a74e36af"
     ],
     [
      7,
      "  load: false"
     ],
     [
      8,
      "  no-cache: false"
     ],
     [
      9,
      "  pull: false"
     ],
     [
      10,
      "  github-token: ***"
     ],
     [
      11,
      "env:"
     ],
     [
      12,
      "  JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/25.0.4-1/x64"
     ],
     [
      13,
      "  JAVA_HOME_25_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/25.0.4-1/x64"
     ],
     [
      14,
      "(node:5537) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead."
     ],
     [
      null,
      "… 665 lines …"
     ],
     [
      680,
      "  },"
     ],
     [
      681,
      "  \"containerimage.digest\": \"sha256:7cba18f1d512b7d7073442d9a9b4c2ea11540764dcb3fe707772660c321fdaac\","
     ],
     [
      682,
      "  \"image.name\": \"ghcr.io/marwanbukhori/queue-gate:7983f0346f1715a0b44d25361ea1a5e0a74e36af\""
     ],
     [
      683,
      "}"
     ],
     [
      684,
      "Reference"
     ],
     [
      685,
      "builder-ec3ced38-5b27-4394-8b8a-f4ac53c3f892/builder-ec3ced38-5b27-4394-8b8a-f4ac53c3f8920/uo4gk83og5fvrz7ff5rdv78te"
     ],
     [
      686,
      "Check build summary support"
     ],
     [
      687,
      "Build summary supported!"
     ]
    ],
    "explain": "The same for queue-gate: one image per service, one tag per commit."
   },
   {
    "name": "Build and push console",
    "result": "success",
    "seconds": 21,
    "log": [
     [
      1,
      "Run docker/build-push-action@v6"
     ],
     [
      2,
      "with:"
     ],
     [
      3,
      "  context: ./console"
     ],
     [
      4,
      "  platforms: linux/amd64"
     ],
     [
      5,
      "  push: true"
     ],
     [
      6,
      "  tags: ghcr.io/marwanbukhori/console:7983f0346f1715a0b44d25361ea1a5e0a74e36af"
     ],
     [
      7,
      "  load: false"
     ],
     [
      8,
      "  no-cache: false"
     ],
     [
      9,
      "  pull: false"
     ],
     [
      10,
      "  github-token: ***"
     ],
     [
      11,
      "env:"
     ],
     [
      12,
      "  JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/25.0.4-1/x64"
     ],
     [
      13,
      "  JAVA_HOME_25_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/25.0.4-1/x64"
     ],
     [
      14,
      "(node:5854) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead."
     ],
     [
      null,
      "… 756 lines …"
     ],
     [
      771,
      "  },"
     ],
     [
      772,
      "  \"containerimage.digest\": \"sha256:c59f24a17cb2baa3b242d1cb8a8cc13a04964b6b21ad12e7b6c38176f929c321\","
     ],
     [
      773,
      "  \"image.name\": \"ghcr.io/marwanbukhori/console:7983f0346f1715a0b44d25361ea1a5e0a74e36af\""
     ],
     [
      774,
      "}"
     ],
     [
      775,
      "Reference"
     ],
     [
      776,
      "builder-ec3ced38-5b27-4394-8b8a-f4ac53c3f892/builder-ec3ced38-5b27-4394-8b8a-f4ac53c3f8920/ow85zewjmdvxioy32d5010jfq"
     ],
     [
      777,
      "Check build summary support"
     ],
     [
      778,
      "Build summary supported!"
     ]
    ],
    "explain": "The same for the console, which also carries the Angular UI you are reading."
   },
   {
    "name": "Verify images are linux/amd64",
    "result": "success",
    "seconds": 1,
    "log": [
     [
      1,
      "Run # Without pipefail, a failing imagetools inspect is masked by tee's"
     ],
     [
      2,
      "# Without pipefail, a failing imagetools inspect is masked by tee's"
     ],
     [
      3,
      "# exit code; the grep below then fails for the wrong reason."
     ],
     [
      4,
      "set -o pipefail"
     ],
     [
      5,
      "for svc in booking-service queue-gate console; do"
     ],
     [
      6,
      "  image=\"ghcr.io/marwanbukhori/${svc}:7983f0346f1715a0b44d25361ea1a5e0a74e36af\""
     ],
     [
      7,
      "  echo \"== ${image}\""
     ],
     [
      8,
      "  docker buildx imagetools inspect \"${image}\" | tee /tmp/inspect.txt"
     ],
     [
      9,
      "  grep -q 'linux/amd64' /tmp/inspect.txt \\"
     ],
     [
      10,
      "    || { echo \"::error::${image} is not linux/amd64\"; exit 1; }"
     ],
     [
      11,
      "done"
     ],
     [
      12,
      "shell: /usr/bin/bash -e {0}"
     ],
     [
      13,
      "env:"
     ],
     [
      14,
      "  JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/25.0.4-1/x64"
     ],
     [
      null,
      "… 41 lines …"
     ],
     [
      56,
      "  Platform:    linux/amd64"
     ],
     [
      57,
      "               "
     ],
     [
      58,
      "  Name:        ghcr.io/marwanbukhori/console:7983f0346f1715a0b44d25361ea1a5e0a74e36af@sha256:56b93ffdca044a5d13c7bd0a52835faac434561fd5346c4ea4e1909b8d05f475"
     ],
     [
      59,
      "  MediaType:   application/vnd.oci.image.manifest.v1+json"
     ],
     [
      60,
      "  Platform:    unknown/unknown"
     ],
     [
      61,
      "  Annotations: "
     ],
     [
      62,
      "    vnd.docker.reference.digest: sha256:28a7888c7509b992b51aa39819e1e121b7e3c713121029f6304290d7147e8e05"
     ],
     [
      63,
      "    vnd.docker.reference.type:   attestation-manifest"
     ]
    ],
    "explain": "Inspects each pushed manifest and fails if any image is not linux/amd64. An image built for the wrong architecture would pass every test here and then fail to start on the cluster."
   },
   {
    "name": "Summary",
    "result": "success",
    "seconds": 0,
    "log": [
     [
      1,
      "Run {"
     ],
     [
      2,
      "{"
     ],
     [
      3,
      "  echo \"### Images published\""
     ],
     [
      4,
      "  echo"
     ],
     [
      5,
      "  echo '```'"
     ],
     [
      6,
      "  echo \"ghcr.io/marwanbukhori/booking-service:7983f0346f1715a0b44d25361ea1a5e0a74e36af\""
     ],
     [
      7,
      "  echo \"ghcr.io/marwanbukhori/queue-gate:7983f0346f1715a0b44d25361ea1a5e0a74e36af\""
     ],
     [
      8,
      "  echo \"ghcr.io/marwanbukhori/console:7983f0346f1715a0b44d25361ea1a5e0a74e36af\""
     ],
     [
      9,
      "  echo '```'"
     ],
     [
      10,
      "  echo"
     ],
     [
      11,
      "  echo \"Deploy with:\""
     ],
     [
      12,
      "  echo '```bash'"
     ],
     [
      13,
      "  echo \"ansible-playbook -i deploy/ansible/inventory.ini \\\\\""
     ],
     [
      14,
      "  echo \"  deploy/ansible/deploy.yml -e image_tag=7983f0346f1715a0b44d25361ea1a5e0a74e36af\""
     ],
     [
      null,
      "… 5 lines …"
     ],
     [
      20,
      "  echo"
     ],
     [
      21,
      "  echo \"Do NOT deploy with \\`oc apply -k\\` on a stale overlay — it\""
     ],
     [
      22,
      "  echo \"reverts the cluster to whatever tags are pinned in git.\""
     ],
     [
      23,
      "} >> \"$GITHUB_STEP_SUMMARY\""
     ],
     [
      24,
      "shell: /usr/bin/bash -e {0}"
     ],
     [
      25,
      "env:"
     ],
     [
      26,
      "  JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/25.0.4-1/x64"
     ],
     [
      27,
      "  JAVA_HOME_25_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/25.0.4-1/x64"
     ]
    ],
    "explain": "Writes what happened to the run's summary page."
   },
   {
    "name": "Complete job",
    "result": "success",
    "seconds": 0,
    "log": [
     [
      1,
      "Cleaning up orphan processes"
     ],
     [
      2,
      "##[warning]Node.js 20 is deprecated. The following actions target Node.js 20 but are being forced to run on Node.js 24: actions/checkout@v4, actions/setup-java@…"
     ]
    ],
    "explain": "The runner is discarded."
   }
  ]
 },
 {
  "kind": "cd",
  "note": "",
  "workflow": "CD",
  "job": "deploy",
  "runId": 36157668802,
  "attempt": 1,
  "url": "https://github.com/marwanbukhori/rembayung-queue/actions/runs/36157668802",
  "commit": "7983f03",
  "startedAt": "2026-09-25T15:57:54Z",
  "result": "success",
  "seconds": 201,
  "steps": [
   {
    "name": "Set up job",
    "result": "success",
    "seconds": 0,
    "log": [
     [
      1,
      "Current runner version: '2.337.0'"
     ],
     [
      2,
      "Runner Image Provisioner"
     ],
     [
      3,
      "Hosted Compute Agent"
     ],
     [
      4,
      "Version: 20260828.587"
     ],
     [
      5,
      "Commit: abac92662cab4cc7352de4f9f9d2e2419aad9c29"
     ],
     [
      6,
      "Build Date: 2026-08-28T16:44:25Z"
     ],
     [
      7,
      "Worker ID: {d530f9f4-57b5-4f26-bfec-cceb2b8c7c13}"
     ],
     [
      8,
      "Azure Region: centralus"
     ],
     [
      9,
      "Operating System"
     ],
     [
      10,
      "Ubuntu"
     ],
     [
      11,
      "24.04.5"
     ],
     [
      12,
      "LTS"
     ],
     [
      13,
      "Runner Image"
     ],
     [
      14,
      "Image: ubuntu-24.04"
     ],
     [
      null,
      "… 5 lines …"
     ],
     [
      20,
      "Metadata: read"
     ],
     [
      21,
      "Secret source: Actions"
     ],
     [
      22,
      "Cache mode: write"
     ],
     [
      23,
      "Prepare workflow directory"
     ],
     [
      24,
      "Prepare all required actions"
     ],
     [
      25,
      "Getting action download info"
     ],
     [
      26,
      "Download action repository 'actions/checkout@v4' (SHA:11d5960a326750d5838078e36cf38b85af677262)"
     ],
     [
      27,
      "Complete job name: deploy"
     ]
    ],
    "explain": "GitHub provisions a fresh ubuntu-latest runner for this one job. Nothing carries over from the previous run, so every build starts from a clean machine."
   },
   {
    "name": "Run actions/checkout@v4",
    "result": "success",
    "seconds": 2,
    "log": [
     [
      1,
      "Run actions/checkout@v4"
     ],
     [
      2,
      "with:"
     ],
     [
      3,
      "  repository: marwanbukhori/rembayung-queue"
     ],
     [
      4,
      "  token: ***"
     ],
     [
      5,
      "  ssh-strict: true"
     ],
     [
      6,
      "  ssh-user: git"
     ],
     [
      7,
      "  persist-credentials: true"
     ],
     [
      8,
      "  clean: true"
     ],
     [
      9,
      "  sparse-checkout-cone-mode: true"
     ],
     [
      10,
      "  fetch-depth: 1"
     ],
     [
      11,
      "  fetch-tags: false"
     ],
     [
      12,
      "  show-progress: true"
     ],
     [
      13,
      "  lfs: false"
     ],
     [
      14,
      "  submodules: false"
     ],
     [
      null,
      "… 43 lines …"
     ],
     [
      58,
      "[command]/usr/bin/git sparse-checkout disable"
     ],
     [
      59,
      "[command]/usr/bin/git config --local --unset-all extensions.worktreeConfig"
     ],
     [
      60,
      "Checking out the ref"
     ],
     [
      61,
      "[command]/usr/bin/git checkout --progress --force -B main refs/remotes/origin/main"
     ],
     [
      62,
      "Switched to a new branch 'main'"
     ],
     [
      63,
      "branch 'main' set up to track 'origin/main'."
     ],
     [
      64,
      "[command]/usr/bin/git log -1 --format=%H"
     ],
     [
      65,
      "7983f0346f1715a0b44d25361ea1a5e0a74e36af"
     ]
    ],
    "explain": "Checks out the exact commit that was pushed. Every image tag later in the pipeline is this commit's SHA."
   },
   {
    "name": "Install Ansible and the Kubernetes client library",
    "result": "success",
    "seconds": 30,
    "log": [
     [
      1,
      "Run python3 -m pip install --upgrade pip"
     ],
     [
      2,
      "python3 -m pip install --upgrade pip"
     ],
     [
      3,
      "python3 -m pip install ansible kubernetes"
     ],
     [
      4,
      "ansible-galaxy collection install -r deploy/ansible/requirements.yml"
     ],
     [
      5,
      "shell: /usr/bin/bash -e {0}"
     ],
     [
      6,
      "Defaulting to user installation because normal site-packages is not writeable"
     ],
     [
      7,
      "Requirement already satisfied: pip in /usr/lib/python3/dist-packages (24.0)"
     ],
     [
      8,
      "Collecting pip"
     ],
     [
      9,
      "  Downloading pip-26.2.1-py3-none-any.whl.metadata (4.6 kB)"
     ],
     [
      10,
      "Downloading pip-26.2.1-py3-none-any.whl (1.8 MB)"
     ],
     [
      11,
      "   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 22.8 MB/s eta 0:00:00"
     ],
     [
      12,
      "Installing collected packages: pip"
     ],
     [
      13,
      "Successfully installed pip-26.2.1"
     ],
     [
      14,
      "Defaulting to user installation because normal site-packages is not writeable"
     ],
     [
      null,
      "… 60 lines …"
     ],
     [
      75,
      "   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 807.9/807.9 kB 182.5 MB/s  0:00:00"
     ],
     [
      76,
      "Downloading websocket_client-1.9.2-py3-none-any.whl (95 kB)"
     ],
     [
      77,
      "Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl (24 kB)"
     ],
     [
      78,
      "Installing collected packages: durationpy, websocket-client, resolvelib, requests-oauthlib, PyYAML, propcache, multidict, frozenlist, aiohappyeyeballs, yarl, an…"
     ],
     [
      79,
      ""
     ],
     [
      80,
      "Successfully installed PyYAML-6.0.3 aiohappyeyeballs-2.7.1 aiohttp-3.14.3 aiosignal-1.4.0 ansible-14.4.0 ansible-core-2.21.4 durationpy-0.11 frozenlist-1.8.0 ku…"
     ],
     [
      81,
      "Starting galaxy collection install process"
     ],
     [
      82,
      "Nothing to do. All requested collections are already installed. If you want to reinstall them, consider using `--force`."
     ]
    ],
    "explain": "CD is a separate workflow that starts when ci succeeds on main: CI publishes, and only CD touches the cluster. This installs Ansible and kubernetes.core, which talks to the API directly rather than shelling out to oc, so every task reports ok or changed truthfully."
   },
   {
    "name": "Install kustomize",
    "result": "success",
    "seconds": 0,
    "log": [
     [
      1,
      "Run curl -sSL --fail \\"
     ],
     [
      2,
      "curl -sSL --fail \\"
     ],
     [
      3,
      "  \"https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${KUSTOMIZE_VERSION}/kustomize_v${KUSTOMIZE_VERSION}_linux_amd64.tar.gz\" \\"
     ],
     [
      4,
      "  | tar -xz -C /usr/local/bin kustomize"
     ],
     [
      5,
      "kustomize version"
     ],
     [
      6,
      "shell: /usr/bin/bash -e {0}"
     ],
     [
      7,
      "env:"
     ],
     [
      8,
      "  KUSTOMIZE_VERSION: 5.4.3"
     ],
     [
      9,
      "v5.4.3"
     ]
    ],
    "explain": "Installs kustomize, to render the same overlay a person would apply by hand."
   },
   {
    "name": "Authenticate to OpenShift",
    "result": "success",
    "seconds": 0,
    "log": [
     [
      1,
      "Run # K8S_AUTH_* is what kubernetes.core reads. Never echo the token."
     ],
     [
      2,
      "# K8S_AUTH_* is what kubernetes.core reads. Never echo the token."
     ],
     [
      3,
      "echo \"K8S_AUTH_HOST=https://api.rm3.7wse.p1.openshiftapps.com:6443\" >> \"$GITHUB_ENV\""
     ],
     [
      4,
      "echo \"K8S_AUTH_API_KEY=${OPENSHIFT_TOKEN}\" >> \"$GITHUB_ENV\""
     ],
     [
      5,
      "shell: /usr/bin/bash -e {0}"
     ],
     [
      6,
      "env:"
     ],
     [
      7,
      "  OPENSHIFT_TOKEN: ***"
     ]
    ],
    "explain": "Exports the cluster URL and a ServiceAccount token from the sandbox environment's secrets, never echoed. That ServiceAccount cannot read Secrets and cannot change RBAC, so a leaked token cannot widen its own access."
   },
   {
    "name": "Resolve the tag to deploy",
    "result": "success",
    "seconds": 0,
    "log": [
     [
      1,
      "Run if [ \"workflow_run\" = \"workflow_dispatch\" ]; then"
     ],
     [
      2,
      "if [ \"workflow_run\" = \"workflow_dispatch\" ]; then"
     ],
     [
      3,
      "  tag=\"\""
     ],
     [
      4,
      "else"
     ],
     [
      5,
      "  # The SHA CI built and published, not github.sha — which on a"
     ],
     [
      6,
      "  # workflow_run points at the default branch head and can differ."
     ],
     [
      7,
      "  tag=\"7983f0346f1715a0b44d25361ea1a5e0a74e36af\""
     ],
     [
      8,
      "fi"
     ],
     [
      9,
      "echo \"IMAGE_TAG=${tag}\" >> \"$GITHUB_ENV\""
     ],
     [
      10,
      "echo \"deploying tag ${tag}\""
     ],
     [
      11,
      "shell: /usr/bin/bash -e {0}"
     ],
     [
      12,
      "env:"
     ],
     [
      13,
      "  K8S_AUTH_HOST: https://api.rm3.7wse.p1.openshiftapps.com:6443"
     ],
     [
      14,
      "  K8S_AUTH_API_KEY: ***"
     ],
     [
      15,
      "deploying tag 7983f0346f1715a0b44d25361ea1a5e0a74e36af"
     ]
    ],
    "explain": "Picks the commit SHA that CI just published. A manual dispatch can name any earlier tag, which is how a rollback by hand works."
   },
   {
    "name": "Deploy",
    "result": "success",
    "seconds": 166,
    "log": [
     [
      1,
      "Run ansible-playbook \\"
     ],
     [
      12,
      "PLAY [Deploy Rembayung to OpenShift] *******************************************"
     ],
     [
      14,
      "TASK [rembayung : Discover current state and validate inputs] ******************"
     ],
     [
      17,
      "TASK [rembayung : Require an explicit image_tag] *******************************"
     ],
     [
      18,
      "ok: [localhost] => {"
     ],
     [
      20,
      "    \"msg\": \"All assertions passed\""
     ],
     [
      23,
      "TASK [rembayung : Read the image currently running on each Deployment] *********"
     ],
     [
      24,
      "ok: [localhost] => (item=booking-service)"
     ],
     [
      25,
      "ok: [localhost] => (item=queue-gate)"
     ],
     [
      26,
      "ok: [localhost] => (item=console)"
     ],
     [
      28,
      "TASK [rembayung : Build the per-service map of currently running tags] *********"
     ],
     [
      29,
      "ok: [localhost]"
     ],
     [
      31,
      "TASK [rembayung : Read the public Route] ***************************************"
     ],
     [
      32,
      "ok: [localhost]"
     ],
     [
      34,
      "TASK [rembayung : Require that the Route exists] *******************************"
     ],
     [
      35,
      "ok: [localhost] => {"
     ],
     [
      37,
      "    \"msg\": \"All assertions passed\""
     ],
     [
      40,
      "TASK [rembayung : Store the Route host] ****************************************"
     ],
     [
      41,
      "ok: [localhost]"
     ],
     [
      43,
      "TASK [rembayung : Refuse to run against a Deployment that is mid-rollout] ******"
     ],
     [
      44,
      "ok: [localhost] => (item=booking-service) => {"
     ],
     [
      562,
      "    \"msg\": \"All assertions passed\""
     ],
     [
      564,
      "ok: [localhost] => (item=queue-gate) => {"
     ],
     [
      1060,
      "    \"msg\": \"All assertions passed\""
     ],
     [
      1062,
      "ok: [localhost] => (item=console) => {"
     ],
     [
      1622,
      "    \"msg\": \"All assertions passed\""
     ],
     [
      1625,
      "TASK [rembayung : Show what is running now] ************************************"
     ],
     [
      1626,
      "ok: [localhost] => {"
     ],
     [
      1627,
      "    \"msg\": \"currently deployed: {'booking-service': '06170aa2b1f83514088e58c2e0b4410da68208e7', 'queue-gate': '06170aa2b1f83514088e58c2e0b4410da68208e7', 'console': '06170aa2b1f83514088e58c2e0b4410da68208e7'} via queue-gate-marwanbukhori-dev.apps.rm3.7wse.p1.openshiftapps.com\""
     ],
     [
      1630,
      "TASK [rembayung : Apply the requested tag and wait for the rollout] ************"
     ],
     [
      1633,
      "TASK [rembayung : Create a scratch copy of the manifests, so the working tree is never edited] ***"
     ],
     [
      1634,
      "changed: [localhost]"
     ],
     [
      1636,
      "TASK [rembayung : Copy the base and the overlay into it] ***********************"
     ],
     [
      1637,
      "changed: [localhost] => (item=base)"
     ],
     [
      1638,
      "changed: [localhost] => (item=overlays/sandbox)"
     ],
     [
      1640,
      "TASK [rembayung : Pin every image in the scratch overlay to the tag being deployed] ***"
     ],
     [
      1641,
      "changed: [localhost] => (item=booking-service)"
     ],
     [
      1642,
      "changed: [localhost] => (item=queue-gate)"
     ],
     [
      1643,
      "changed: [localhost] => (item=console)"
     ],
     [
      1645,
      "TASK [rembayung : Render the manifests, keeping only the kinds CD may write] ***"
     ],
     [
      1646,
      "ok: [localhost]"
     ],
     [
      1648,
      "TASK [rembayung : Every service must be pinned to the tag being deployed] ******"
     ],
     [
      1649,
      "ok: [localhost] => (item=booking-service) => {"
     ],
     [
      1653,
      "    \"msg\": \"All assertions passed\""
     ],
     [
      1655,
      "ok: [localhost] => (item=queue-gate) => {"
     ],
     [
      1659,
      "    \"msg\": \"All assertions passed\""
     ],
     [
      1661,
      "ok: [localhost] => (item=console) => {"
     ],
     [
      1665,
      "    \"msg\": \"All assertions passed\""
     ],
     [
      1668,
      "TASK [rembayung : Write the rendered manifests out for the apply] **************"
     ],
     [
      1669,
      "changed: [localhost]"
     ],
     [
      1671,
      "TASK [rembayung : Apply the manifests] *****************************************"
     ],
     [
      1672,
      "changed: [localhost]"
     ],
     [
      1674,
      "TASK [rembayung : Set the image on each Deployment] ****************************"
     ],
     [
      1675,
      "ok: [localhost] => (item=booking-service)"
     ],
     [
      1676,
      "ok: [localhost] => (item=queue-gate)"
     ],
     [
      1677,
      "ok: [localhost] => (item=console)"
     ],
     [
      1679,
      "TASK [rembayung : Wait for both rollouts to complete] **************************"
     ],
     [
      1680,
      "ok: [localhost] => (item=booking-service)"
     ],
     [
      1681,
      "ok: [localhost] => (item=queue-gate)"
     ],
     [
      1682,
      "ok: [localhost] => (item=console)"
     ],
     [
      1684,
      "TASK [rembayung : Remove the scratch copy] *************************************"
     ],
     [
      1685,
      "changed: [localhost]"
     ],
     [
      1687,
      "TASK [rembayung : Smoke-test the public Route] *********************************"
     ],
     [
      1690,
      "TASK [rembayung : Join the queue through the public Route] *********************"
     ],
     [
      1691,
      "ok: [localhost]"
     ],
     [
      1693,
      "TASK [rembayung : Check the token's status when one was issued] ****************"
     ],
     [
      1694,
      "ok: [localhost]"
     ],
     [
      1696,
      "TASK [rembayung : Read the HEC URL out of the splunk-hec Secret] ***************"
     ],
     [
      1697,
      "ok: [localhost]"
     ],
     [
      1699,
      "TASK [rembayung : Fail when SPLUNK_HEC_URL carries a path] *********************"
     ],
     [
      1700,
      "skipping: [localhost]"
     ],
     [
      1702,
      "TASK [rembayung : Confirm booking-service is Ready] ****************************"
     ],
     [
      1703,
      "ok: [localhost]"
     ],
     [
      1705,
      "TASK [rembayung : Decide whether the smoke test passed] ************************"
     ],
     [
      1706,
      "ok: [localhost]"
     ],
     [
      1708,
      "TASK [rembayung : Report the smoke result] *************************************"
     ],
     [
      1709,
      "ok: [localhost] => {"
     ],
     [
      1710,
      "    \"msg\": \"smoke: queue=200 booking-service ready replicas=2 passed=True\""
     ],
     [
      1713,
      "TASK [rembayung : Fail if the smoke test did not pass] *************************"
     ],
     [
      1714,
      "skipping: [localhost]"
     ],
     [
      1716,
      "PLAY RECAP *********************************************************************"
     ],
     [
      1717,
      "localhost                  : ok=27   changed=6    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0   "
     ]
    ],
    "explain": "The playbook, in order: read what is running now and refuse to start mid-rollout; render the overlay with every image pinned to this tag and apply only the kinds CD may write; wait for all three rollouts; smoke-test the public queue path. The checks come first so a bad input stops before anything changes; any failure after the first change rolls back."
   },
   {
    "name": "Summary",
    "result": "success",
    "seconds": 0,
    "log": [
     [
      1,
      "Run {"
     ],
     [
      2,
      "{"
     ],
     [
      3,
      "  echo \"### CD\""
     ],
     [
      4,
      "  echo \"\""
     ],
     [
      5,
      "  echo \"Tag: \\`${IMAGE_TAG:-not resolved — failed before tag selection}\\`\""
     ],
     [
      6,
      "  echo \"\""
     ],
     [
      7,
      "  echo \"Result: success\""
     ],
     [
      8,
      "  echo \"\""
     ],
     [
      9,
      "  echo \"Redeploy a previous tag from the Actions tab via Run workflow.\""
     ],
     [
      10,
      "} >> \"$GITHUB_STEP_SUMMARY\""
     ],
     [
      11,
      "shell: /usr/bin/bash -e {0}"
     ],
     [
      12,
      "env:"
     ],
     [
      13,
      "  K8S_AUTH_HOST: https://api.rm3.7wse.p1.openshiftapps.com:6443"
     ],
     [
      14,
      "  K8S_AUTH_API_KEY: ***"
     ],
     [
      15,
      "  IMAGE_TAG: 7983f0346f1715a0b44d25361ea1a5e0a74e36af"
     ]
    ],
    "explain": "Writes what happened to the run's summary page."
   },
   {
    "name": "Complete job",
    "result": "success",
    "seconds": 0,
    "log": [
     [
      1,
      "Evaluate and set environment url"
     ],
     [
      2,
      "Evaluated environment url: https://queue-gate-marwanbukhori-dev.apps.rm3.7wse.p1.openshiftapps.com"
     ],
     [
      3,
      "Cleaning up orphan processes"
     ],
     [
      4,
      "##[warning]Node.js 20 is deprecated. The following actions target Node.js 20 but are being forced to run on Node.js 24: actions/checkout@v4. For more informatio…"
     ]
    ],
    "explain": "The runner is discarded."
   }
  ]
 },
 {
  "kind": "rollback",
  "note": "CD of 95ba6af, first attempt. booking-service did not become ready inside the wait, so the playbook put every service back on the tag it had been running and failed loudly. The public site answered throughout, and a re-run of the same image passed.",
  "workflow": "CD",
  "job": "deploy",
  "runId": 36142971533,
  "attempt": 1,
  "url": "https://github.com/marwanbukhori/rembayung-queue/actions/runs/36142971533/job/108097025561",
  "commit": "95ba6af",
  "startedAt": "2026-09-25T13:45:18Z",
  "result": "failure",
  "seconds": 449,
  "steps": [
   {
    "name": "Set up job",
    "result": "success",
    "seconds": 1,
    "log": [
     [
      1,
      "Current runner version: '2.337.0'"
     ],
     [
      2,
      "Runner Image Provisioner"
     ],
     [
      3,
      "Hosted Compute Agent"
     ],
     [
      4,
      "Version: 20260828.587"
     ],
     [
      5,
      "Commit: abac92662cab4cc7352de4f9f9d2e2419aad9c29"
     ],
     [
      6,
      "Build Date: 2026-08-28T16:44:25Z"
     ],
     [
      7,
      "Worker ID: {1b67b4a9-980c-4736-9294-d9126b2bf8d1}"
     ],
     [
      8,
      "Azure Region: westus3"
     ],
     [
      9,
      "Operating System"
     ],
     [
      10,
      "Ubuntu"
     ],
     [
      11,
      "24.04.5"
     ],
     [
      12,
      "LTS"
     ],
     [
      13,
      "Runner Image"
     ],
     [
      14,
      "Image: ubuntu-24.04"
     ],
     [
      null,
      "… 5 lines …"
     ],
     [
      20,
      "Metadata: read"
     ],
     [
      21,
      "Secret source: Actions"
     ],
     [
      22,
      "Cache mode: write"
     ],
     [
      23,
      "Prepare workflow directory"
     ],
     [
      24,
      "Prepare all required actions"
     ],
     [
      25,
      "Getting action download info"
     ],
     [
      26,
      "Download action repository 'actions/checkout@v4' (SHA:11d5960a326750d5838078e36cf38b85af677262)"
     ],
     [
      27,
      "Complete job name: deploy"
     ]
    ],
    "explain": "GitHub provisions a fresh ubuntu-latest runner for this one job. Nothing carries over from the previous run, so every build starts from a clean machine."
   },
   {
    "name": "Run actions/checkout@v4",
    "result": "success",
    "seconds": 1,
    "log": [
     [
      1,
      "Run actions/checkout@v4"
     ],
     [
      2,
      "with:"
     ],
     [
      3,
      "  repository: marwanbukhori/rembayung-queue"
     ],
     [
      4,
      "  token: ***"
     ],
     [
      5,
      "  ssh-strict: true"
     ],
     [
      6,
      "  ssh-user: git"
     ],
     [
      7,
      "  persist-credentials: true"
     ],
     [
      8,
      "  clean: true"
     ],
     [
      9,
      "  sparse-checkout-cone-mode: true"
     ],
     [
      10,
      "  fetch-depth: 1"
     ],
     [
      11,
      "  fetch-tags: false"
     ],
     [
      12,
      "  show-progress: true"
     ],
     [
      13,
      "  lfs: false"
     ],
     [
      14,
      "  submodules: false"
     ],
     [
      null,
      "… 43 lines …"
     ],
     [
      58,
      "[command]/usr/bin/git sparse-checkout disable"
     ],
     [
      59,
      "[command]/usr/bin/git config --local --unset-all extensions.worktreeConfig"
     ],
     [
      60,
      "Checking out the ref"
     ],
     [
      61,
      "[command]/usr/bin/git checkout --progress --force -B main refs/remotes/origin/main"
     ],
     [
      62,
      "Switched to a new branch 'main'"
     ],
     [
      63,
      "branch 'main' set up to track 'origin/main'."
     ],
     [
      64,
      "[command]/usr/bin/git log -1 --format=%H"
     ],
     [
      65,
      "95ba6af689a50fe4d2102a53ccc43a1e8d598b90"
     ]
    ],
    "explain": "Checks out the exact commit that was pushed. Every image tag later in the pipeline is this commit's SHA."
   },
   {
    "name": "Install Ansible and the Kubernetes client library",
    "result": "success",
    "seconds": 28,
    "log": [
     [
      1,
      "Run python3 -m pip install --upgrade pip"
     ],
     [
      2,
      "python3 -m pip install --upgrade pip"
     ],
     [
      3,
      "python3 -m pip install ansible kubernetes"
     ],
     [
      4,
      "ansible-galaxy collection install -r deploy/ansible/requirements.yml"
     ],
     [
      5,
      "shell: /usr/bin/bash -e {0}"
     ],
     [
      6,
      "Defaulting to user installation because normal site-packages is not writeable"
     ],
     [
      7,
      "Requirement already satisfied: pip in /usr/lib/python3/dist-packages (24.0)"
     ],
     [
      8,
      "Collecting pip"
     ],
     [
      9,
      "  Downloading pip-26.2.1-py3-none-any.whl.metadata (4.6 kB)"
     ],
     [
      10,
      "Downloading pip-26.2.1-py3-none-any.whl (1.8 MB)"
     ],
     [
      11,
      "   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 43.7 MB/s eta 0:00:00"
     ],
     [
      12,
      "Installing collected packages: pip"
     ],
     [
      13,
      "Successfully installed pip-26.2.1"
     ],
     [
      14,
      "Defaulting to user installation because normal site-packages is not writeable"
     ],
     [
      null,
      "… 60 lines …"
     ],
     [
      75,
      "   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 807.9/807.9 kB 178.4 MB/s  0:00:00"
     ],
     [
      76,
      "Downloading websocket_client-1.9.2-py3-none-any.whl (95 kB)"
     ],
     [
      77,
      "Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl (24 kB)"
     ],
     [
      78,
      "Installing collected packages: durationpy, websocket-client, resolvelib, requests-oauthlib, PyYAML, propcache, multidict, frozenlist, aiohappyeyeballs, yarl, an…"
     ],
     [
      79,
      ""
     ],
     [
      80,
      "Successfully installed PyYAML-6.0.3 aiohappyeyeballs-2.7.1 aiohttp-3.14.3 aiosignal-1.4.0 ansible-14.4.0 ansible-core-2.21.4 durationpy-0.11 frozenlist-1.8.0 ku…"
     ],
     [
      81,
      "Starting galaxy collection install process"
     ],
     [
      82,
      "Nothing to do. All requested collections are already installed. If you want to reinstall them, consider using `--force`."
     ]
    ],
    "explain": "CD is a separate workflow that starts when ci succeeds on main: CI publishes, and only CD touches the cluster. This installs Ansible and kubernetes.core, which talks to the API directly rather than shelling out to oc, so every task reports ok or changed truthfully."
   },
   {
    "name": "Install kustomize",
    "result": "success",
    "seconds": 0,
    "log": [
     [
      1,
      "Run curl -sSL --fail \\"
     ],
     [
      2,
      "curl -sSL --fail \\"
     ],
     [
      3,
      "  \"https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${KUSTOMIZE_VERSION}/kustomize_v${KUSTOMIZE_VERSION}_linux_amd64.tar.gz\" \\"
     ],
     [
      4,
      "  | tar -xz -C /usr/local/bin kustomize"
     ],
     [
      5,
      "kustomize version"
     ],
     [
      6,
      "shell: /usr/bin/bash -e {0}"
     ],
     [
      7,
      "env:"
     ],
     [
      8,
      "  KUSTOMIZE_VERSION: 5.4.3"
     ],
     [
      9,
      "v5.4.3"
     ]
    ],
    "explain": "Installs kustomize, to render the same overlay a person would apply by hand."
   },
   {
    "name": "Authenticate to OpenShift",
    "result": "success",
    "seconds": 0,
    "log": [
     [
      1,
      "Run # K8S_AUTH_* is what kubernetes.core reads. Never echo the token."
     ],
     [
      2,
      "# K8S_AUTH_* is what kubernetes.core reads. Never echo the token."
     ],
     [
      3,
      "echo \"K8S_AUTH_HOST=https://api.rm3.7wse.p1.openshiftapps.com:6443\" >> \"$GITHUB_ENV\""
     ],
     [
      4,
      "echo \"K8S_AUTH_API_KEY=${OPENSHIFT_TOKEN}\" >> \"$GITHUB_ENV\""
     ],
     [
      5,
      "shell: /usr/bin/bash -e {0}"
     ],
     [
      6,
      "env:"
     ],
     [
      7,
      "  OPENSHIFT_TOKEN: ***"
     ]
    ],
    "explain": "Exports the cluster URL and a ServiceAccount token from the sandbox environment's secrets, never echoed. That ServiceAccount cannot read Secrets and cannot change RBAC, so a leaked token cannot widen its own access."
   },
   {
    "name": "Resolve the tag to deploy",
    "result": "success",
    "seconds": 0,
    "log": [
     [
      1,
      "Run if [ \"workflow_run\" = \"workflow_dispatch\" ]; then"
     ],
     [
      2,
      "if [ \"workflow_run\" = \"workflow_dispatch\" ]; then"
     ],
     [
      3,
      "  tag=\"\""
     ],
     [
      4,
      "else"
     ],
     [
      5,
      "  # The SHA CI built and published, not github.sha — which on a"
     ],
     [
      6,
      "  # workflow_run points at the default branch head and can differ."
     ],
     [
      7,
      "  tag=\"95ba6af689a50fe4d2102a53ccc43a1e8d598b90\""
     ],
     [
      8,
      "fi"
     ],
     [
      9,
      "echo \"IMAGE_TAG=${tag}\" >> \"$GITHUB_ENV\""
     ],
     [
      10,
      "echo \"deploying tag ${tag}\""
     ],
     [
      11,
      "shell: /usr/bin/bash -e {0}"
     ],
     [
      12,
      "env:"
     ],
     [
      13,
      "  K8S_AUTH_HOST: https://api.rm3.7wse.p1.openshiftapps.com:6443"
     ],
     [
      14,
      "  K8S_AUTH_API_KEY: ***"
     ],
     [
      15,
      "deploying tag 95ba6af689a50fe4d2102a53ccc43a1e8d598b90"
     ]
    ],
    "explain": "Picks the commit SHA that CI just published. A manual dispatch can name any earlier tag, which is how a rollback by hand works."
   },
   {
    "name": "Deploy",
    "result": "failure",
    "seconds": 415,
    "log": [
     [
      1,
      "Run ansible-playbook \\"
     ],
     [
      12,
      "PLAY [Deploy Rembayung to OpenShift] *******************************************"
     ],
     [
      14,
      "TASK [rembayung : Discover current state and validate inputs] ******************"
     ],
     [
      17,
      "TASK [rembayung : Require an explicit image_tag] *******************************"
     ],
     [
      18,
      "ok: [localhost] => {"
     ],
     [
      20,
      "    \"msg\": \"All assertions passed\""
     ],
     [
      23,
      "TASK [rembayung : Read the image currently running on each Deployment] *********"
     ],
     [
      24,
      "ok: [localhost] => (item=booking-service)"
     ],
     [
      25,
      "ok: [localhost] => (item=queue-gate)"
     ],
     [
      26,
      "ok: [localhost] => (item=console)"
     ],
     [
      28,
      "TASK [rembayung : Build the per-service map of currently running tags] *********"
     ],
     [
      29,
      "ok: [localhost]"
     ],
     [
      31,
      "TASK [rembayung : Read the public Route] ***************************************"
     ],
     [
      32,
      "ok: [localhost]"
     ],
     [
      34,
      "TASK [rembayung : Require that the Route exists] *******************************"
     ],
     [
      35,
      "ok: [localhost] => {"
     ],
     [
      37,
      "    \"msg\": \"All assertions passed\""
     ],
     [
      40,
      "TASK [rembayung : Store the Route host] ****************************************"
     ],
     [
      41,
      "ok: [localhost]"
     ],
     [
      43,
      "TASK [rembayung : Refuse to run against a Deployment that is mid-rollout] ******"
     ],
     [
      44,
      "ok: [localhost] => (item=booking-service) => {"
     ],
     [
      562,
      "    \"msg\": \"All assertions passed\""
     ],
     [
      564,
      "ok: [localhost] => (item=queue-gate) => {"
     ],
     [
      1060,
      "    \"msg\": \"All assertions passed\""
     ],
     [
      1062,
      "ok: [localhost] => (item=console) => {"
     ],
     [
      1622,
      "    \"msg\": \"All assertions passed\""
     ],
     [
      1625,
      "TASK [rembayung : Show what is running now] ************************************"
     ],
     [
      1626,
      "ok: [localhost] => {"
     ],
     [
      1627,
      "    \"msg\": \"currently deployed: {'booking-service': '1a3e6e1108754e29d30f0eb1fb2891c7970b6f0c', 'queue-gate': '1a3e6e1108754e29d30f0eb1fb2891c7970b6f0c', 'console': '1a3e6e1108754e29d30f0eb1fb2891c7970b6f0c'} via queue-gate-marwanbukhori-dev.apps.rm3.7wse.p1.openshiftapps.com\""
     ],
     [
      1630,
      "TASK [rembayung : Apply the requested tag and wait for the rollout] ************"
     ],
     [
      1633,
      "TASK [rembayung : Create a scratch copy of the manifests, so the working tree is never edited] ***"
     ],
     [
      1634,
      "changed: [localhost]"
     ],
     [
      1636,
      "TASK [rembayung : Copy the base and the overlay into it] ***********************"
     ],
     [
      1637,
      "changed: [localhost] => (item=base)"
     ],
     [
      1638,
      "changed: [localhost] => (item=overlays/sandbox)"
     ],
     [
      1640,
      "TASK [rembayung : Pin every image in the scratch overlay to the tag being deployed] ***"
     ],
     [
      1641,
      "changed: [localhost] => (item=booking-service)"
     ],
     [
      1642,
      "changed: [localhost] => (item=queue-gate)"
     ],
     [
      1643,
      "changed: [localhost] => (item=console)"
     ],
     [
      1645,
      "TASK [rembayung : Render the manifests, keeping only the kinds CD may write] ***"
     ],
     [
      1646,
      "ok: [localhost]"
     ],
     [
      1648,
      "TASK [rembayung : Every service must be pinned to the tag being deployed] ******"
     ],
     [
      1649,
      "ok: [localhost] => (item=booking-service) => {"
     ],
     [
      1653,
      "    \"msg\": \"All assertions passed\""
     ],
     [
      1655,
      "ok: [localhost] => (item=queue-gate) => {"
     ],
     [
      1659,
      "    \"msg\": \"All assertions passed\""
     ],
     [
      1661,
      "ok: [localhost] => (item=console) => {"
     ],
     [
      1665,
      "    \"msg\": \"All assertions passed\""
     ],
     [
      1668,
      "TASK [rembayung : Write the rendered manifests out for the apply] **************"
     ],
     [
      1669,
      "changed: [localhost]"
     ],
     [
      1671,
      "TASK [rembayung : Apply the manifests] *****************************************"
     ],
     [
      1672,
      "changed: [localhost]"
     ],
     [
      1674,
      "TASK [rembayung : Set the image on each Deployment] ****************************"
     ],
     [
      1675,
      "ok: [localhost] => (item=booking-service)"
     ],
     [
      1676,
      "ok: [localhost] => (item=queue-gate)"
     ],
     [
      1677,
      "ok: [localhost] => (item=console)"
     ],
     [
      1679,
      "TASK [rembayung : Wait for both rollouts to complete] **************************"
     ],
     [
      1688,
      "failed: [localhost] (item=booking-service) => {\"ansible_loop_var\": \"item\", \"changed\": false, \"item\": \"booking-service\", \"msg\": \"Failed to gather information about Deployment(s) even after waiting for 303 seconds\"}"
     ],
     [
      1689,
      "ok: [localhost] => (item=queue-gate)"
     ],
     [
      1690,
      "ok: [localhost] => (item=console)"
     ],
     [
      1692,
      "TASK [rembayung : Describe what failed] ****************************************"
     ],
     [
      1693,
      "ok: [localhost]"
     ],
     [
      1695,
      "TASK [rembayung : Roll back] ***************************************************"
     ],
     [
      1698,
      "TASK [rembayung : Announce the rollback] ***************************************"
     ],
     [
      1699,
      "ok: [localhost] => {"
     ],
     [
      1700,
      "    \"msg\": \"DEPLOY FAILED (Wait for both rollouts to complete — One or more items failed). Rolling back to {'booking-service': '1a3e6e1108754e29d30f0eb1fb2891c7970b6f0c', 'queue-gate': '1a3e6e1108754e29d30f0eb1fb2891c7970b6f0c', 'console': '1a3e6e1108754e29d30f0eb1fb2891c7970b6f0c'}.\""
     ],
     [
      1703,
      "TASK [rembayung : Restore each Deployment to the tag it was running] ***********"
     ],
     [
      1704,
      "changed: [localhost] => (item=booking-service)"
     ],
     [
      1705,
      "changed: [localhost] => (item=queue-gate)"
     ],
     [
      1706,
      "changed: [localhost] => (item=console)"
     ],
     [
      1708,
      "TASK [rembayung : Wait for the rollback to complete] ***************************"
     ],
     [
      1709,
      "ok: [localhost] => (item=booking-service)"
     ],
     [
      1710,
      "ok: [localhost] => (item=queue-gate)"
     ],
     [
      1711,
      "ok: [localhost] => (item=console)"
     ],
     [
      1713,
      "TASK [rembayung : Re-check the queue path after rolling back] ******************"
     ],
     [
      1714,
      "ok: [localhost]"
     ],
     [
      1716,
      "TASK [rembayung : Fail loudly, naming both the failed tag and the restored tags] ***"
     ],
     [
      1725,
      "fatal: [localhost]: FAILED! => {\"changed\": false, \"msg\": \"Deploy of 95ba6af689a50fe4d2102a53ccc43a1e8d598b90 failed: Wait for both rollouts to complete — One or more items failed. Rolled back to {'booking-service': '1a3e6e1108754e29d30f0eb1fb2891c7970b6f0c', 'queue-gate': '1a3e6e1108754e29d30f0eb1fb2891c7970b6f0c', 'console': '1a3e6e1108754e29d30f0eb1fb2891c7970b6f0c'}. Rollback rollout: ok. Rollback smoke: ok.\"}"
     ],
     [
      1727,
      "PLAY RECAP *********************************************************************"
     ],
     [
      1728,
      "localhost                  : ok=24   changed=6    unreachable=0    failed=1    skipped=0    rescued=1    ignored=0   "
     ]
    ],
    "explain": "This time booking-service did not become ready inside the wait. The playbook described what failed, restored each Deployment to the tag it had been running, waited for that rollout, re-checked the public queue path, and then failed loudly naming both tags. The site stayed up throughout; the re-run passed."
   },
   {
    "name": "Summary",
    "result": "success",
    "seconds": 0,
    "log": [
     [
      1,
      "Run {"
     ],
     [
      2,
      "{"
     ],
     [
      3,
      "  echo \"### CD\""
     ],
     [
      4,
      "  echo \"\""
     ],
     [
      5,
      "  echo \"Tag: \\`${IMAGE_TAG:-not resolved — failed before tag selection}\\`\""
     ],
     [
      6,
      "  echo \"\""
     ],
     [
      7,
      "  echo \"Result: failure\""
     ],
     [
      8,
      "  echo \"\""
     ],
     [
      9,
      "  echo \"Redeploy a previous tag from the Actions tab via Run workflow.\""
     ],
     [
      10,
      "} >> \"$GITHUB_STEP_SUMMARY\""
     ],
     [
      11,
      "shell: /usr/bin/bash -e {0}"
     ],
     [
      12,
      "env:"
     ],
     [
      13,
      "  K8S_AUTH_HOST: https://api.rm3.7wse.p1.openshiftapps.com:6443"
     ],
     [
      14,
      "  K8S_AUTH_API_KEY: ***"
     ],
     [
      15,
      "  IMAGE_TAG: 95ba6af689a50fe4d2102a53ccc43a1e8d598b90"
     ]
    ],
    "explain": "Writes what happened to the run's summary page."
   }
  ]
 }
];
