apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: marwanbukhori-dev
resources:
  - ../../base
images:
  - name: ghcr.io/marwanbukhori/queue-gate
    newTag: 270288f
  - name: ghcr.io/marwanbukhori/booking-service
    newTag: a98feec
