apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: queue-gate
spec:
  to:
    kind: Service
    name: queue-gate
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
